{{- if (or .Values.nameOverride .Values.persistence.pv.enabled) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "component-pvc.name" . }}
  labels:
    component: {{ template "component-pvc.name" . }}
    chart: {{ template "component-pvc.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.pv.accessMode | quote }}
  capacity:
  {{- if not .Values.persistence.pv.capacity.storage }}
  storage: 100Mi
  {{- else }}
  storage: {{ .Values.persistence.pv.capacity.storage | quote }}
  {{- end }}
  {{- if .Values.persistence.pv.hostPath.path }}
  {{- if (eq "-" .Values.persistence.pv.hostPath.path) }}
  hostPath:
    path: /tmp/{{ .Release.Namespace }}/{{ .Release.Name }}/{{ template "component-pvc.name" . }}
  {{- else }}
  hostPath:
    path: {{ .Values.persistence.pv.hostPath.path | quote }}
  {{- end }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.pv.storageClass }}
  {{- if (eq "-" .Values.persistence.pv.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.pv.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- end }}