apiVersion: v1
kind: Secret
metadata:
  name: {{ template "testops-component-secret.name" . }}
  labels:
    component: {{ template "testops-component-secret.name" . }}
    chart: {{ template "testops-component-secret.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
  {{- with (.Values.metadata).annotations }}
  annotations:
    {{- range $key, $val := . }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  {{- end }}
{{- with .Values.type }}
type: {{ . }}
{{- end }}
{{- with .Values.data }}
data:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end }}
{{- with .Values.stringData }}
stringData:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}